### ISSUE TITLE
SLC granules are to large for current machines

### ISSUE THREAD

**Issue by mnamneus** [asfadmin/hyp3-in-a-box#228]
SLC granules require more memory than expected which can result in an error during processing when run on AWS machines with insufficient RAM (known that m5d.xlarge is too small for SLC).
Should probably add a specifications field for each process and only allow machines that meet it to run that process.
At minimum, better documentation should be given since now it's just a completely obtuse error in the email

**Comment by mnamneus** [comment]
Failure during granule download results in unhelpful error message in email. No possibility for being re-queued. It would be an improvement to send a link in the e-mail to allow the user to re-queue immediately.

**Comment by mnamneus** [comment]
New unknown processing error "died with <Signals.SIGKILL: 9>"
	TRACEBACK FOLLOWS:

/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py:4274: RuntimeWarning: Invalid value encountered in percentile
  interpolation=interpolation)
/home/ubuntu/hyp3-in-a-box/processes/rtc_snap/build/hyp3-rtc-snap/src/byteSigmaScale.py:11: RuntimeWarning: invalid value encountered in greater
  data[data>top]=top
2-sigma cutoffs are 0.152752518654 0.828075647354
/home/ubuntu/hyp3-in-a-box/processes/rtc_snap/build/hyp3-rtc-snap/src/byteSigmaScale.py:27: RuntimeWarning: invalid value encountered in greater
  mask = (data>0).astype(int)
Reading full-pol image (Gamma0_VV_utm_amp.tif)
Reading cross-pol image (Gamma0_VH_utm_amp.tif)
Calculating color decomposition components
Calculate red channel and save in GeoTIFF
Traceback (most recent call last):
  File "/home/ubuntu/hyp3-in-a-box/processes/rtc_snap/build/hyp3-rtc-snap/src/procSentinelRTC-3.py", line 747, in <module>
    cleanTemp=args.cleanTemp,aoi=args.aoi,shape=args.shape)
  File "/home/ubuntu/hyp3-in-a-box/processes/rtc_snap/build/hyp3-rtc-snap/src/procSentinelRTC-3.py", line 651, in procSentinelRTC
    make_out_files("VV","VH",tcOut,utm_subset)
  File "/home/ubuntu/hyp3-in-a-box/processes/rtc_snap/build/hyp3-rtc-snap/src/procSentinelRTC-3.py", line 412, in make_out_files
    make_browse(tcOut,pol,main_file,cp=cp_file)
  File "/home/ubuntu/hyp3-in-a-box/processes/rtc_snap/build/hyp3-rtc-snap/src/procSentinelRTC-3.py", line 319, in make_browse
    rtc2color(ampfile,ampfile2,threshold,colortif,amp=True,cleanup=True)
  File "/home/ubuntu/hyp3-in-a-box/processes/rtc_snap/build/hyp3-rtc-snap/src/rtc2color.py", line 105, in rtc2color
    red = (2.0*rp*(1 - blue_mask) + zp*blue_mask)*255
MemoryError

ran twice to check reproduceability on granule
S1B_EW_GRDM_1SDV_20180925T071808_20180925T071908_012868_017C2D_F98C
both runs produced identical tracebacks and runtime warnings

**Comment by mnamneus** [comment]
download links in emails seem to expire (expired token error on clicking links at least up to 11hrs old) could allow the user to specify an s3 bucket to dump the processed granules in. That way even if the token expires they can access the bucket. Would also mean that they could delete old granules once downloaded or not needed to save money.
